1. Create a class Employee and then do the following

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [1]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sowmya", "Doneti", 200000, "IT")
employee2 = Employee("Divya", "Doneti", 100000, "HR")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Aishwarya", "Pasumarthy", 90000, "Finance")
fulltime_employee2 = FulltimeEmployee("Sravani", "Kakarla", 80000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)

Average Salary for Employees: 75000.0
Average Salary for Fulltime Employees: 42500.0


2. Numpy
Using NumPy

• create random vector of size 20 having only float in the range 1-20.

• Then reshape the array to 4 by 5

•Then replace the max in each row by 0 (axis=1)

(you can NOT implement it via for loop)

In [2]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 1.21417201 13.72206087  3.69395133  5.13678035 13.63686956 12.32635586
 12.69749355 14.74491772  4.60818415 10.91818508  2.42792306 10.73722096
  4.61403554 12.77115483 14.67241021  6.60721304  4.86627505  7.89821613
  2.56885948  8.42527139]


In [3]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[ 1.21417201 13.72206087  3.69395133  5.13678035 13.63686956]
 [12.32635586 12.69749355 14.74491772  4.60818415 10.91818508]
 [ 2.42792306 10.73722096  4.61403554 12.77115483 14.67241021]
 [ 6.60721304  4.86627505  7.89821613  2.56885948  8.42527139]]


In [4]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 1.21417201  0.          3.69395133  5.13678035 13.63686956]
 [12.32635586 12.69749355  0.          4.60818415 10.91818508]
 [ 2.42792306 10.73722096  4.61403554 12.77115483  0.        ]
 [ 6.60721304  4.86627505  7.89821613  2.56885948  0.        ]]
